CREATE DATABASE IF NOT EXISTS tictactoe;

USE tictactoe;

CREATE TABLE IF NOT EXISTS users (
    uid VARCHAR(64) NOT NULL PRIMARY KEY,
    name VARCHAR(100) DEFAULT NULL,
    elo_rating INT NOT NULL DEFAULT 1200,
    is_online BOOLEAN NOT NULL DEFAULT FALSE
);
